LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
$(warning LOCAL_PATH = $(LOCAL_PATH))

LOCAL_MODULE := libFM1388Parameter
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_SHARED_LIBRARIES)
LOCAL_SRC_FILES := libFM1388Parameter.c 

include $(BUILD_SHARED_LIBRARY)


