#include $(DBG_DRIVERS_PATH)/config_$(DBG_SOC)
include $(DBG_ROOT_PATH)/build/build.mk
include $(DBG_DRIVERS_PATH)/drivers.mk

obj-y	:=  accel/ drivers_dbg/ gps/ touchscreen/ interface/\
		misc_devices/ powermanager/ dsi83/ lpc/ saf7741/\
		flysemdriver/ drivers_loader/ misc/ flyparameter/\
		temp/ button/ tef6638/ sound_det/ uvc_cam/ flycam/\
		i2c_devices_probe/ lowmemorykillprotectlist/\
		factory_machine_patch/ fm1388/ hal_comm/ module_comm/\
		bare_para/ ad/ detect_carback/ ds90ub9xx/ s32k_ipc/ test_spi\
